version: "3.7"
services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: debezium/zookeeper:1.0
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
      - kafka-connect

  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:5.4.0 
    ports:
     - 9092:9092
    networks:
      - kafka-connect
    environment:
     - KAFKA_BROKER_ID=1 
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  kafka-connect:
    container_name: kafka-connect
    image: debezium/connect:1.0
    ports:
     - 8083:8083
    networks:
      - kafka-connect
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=cdc_configs
     - OFFSET_STORAGE_TOPIC=cdc_offsets
     - STATUS_STORAGE_TOPIC=cdc_statuses
    volumes:
     - "./target/kafka-connect-redis-connector-1.1:/kafka/connect/kafka-connect-redis-connector"

  
  kafka-connect-ui:
    container_name: kafka-connect-ui
    image: landoop/kafka-connect-ui:0.9.7
    ports:
      - 8888:8000
    networks:
      - kafka-connect
    environment:
      - CONNECT_URL=http://kafka-connect:8083

  control-center:
    container_name: control-center
    image: confluentinc/cp-enterprise-control-center:5.4.0
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "9021:9021"
      - "9022:9022"
    networks:
      - kafka-connect
    environment:
      - CONTROL_CENTER_BOOTSTRAP_SERVERS=kafka:9092
      - CONTROL_CENTER_ZOOKEEPER_CONNECT=zookeeper:2181
      - CONTROL_CENTER_REPLICATION_FACTOR=1
      - CONTROL_CENTER_CONNECT_CLUSTER=http://kafka-connect:8083

  redis:
    container_name: redis
    image: redis:5-alpine
    ports:
      - 6379:6379
    networks:
      - kafka-connect
networks:
  kafka-connect:
